language: python
sudo: false
python:
  - "3.6"      
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install numpy
  #- python setup.py install
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
  - pytest
